Request for reviewers to review mi code
Stevers1/My-Portfolio pull request #2
Opened 2022-06-30 21:30 UTC by Stevers1

Long live microverse.

2022-06-30 23:03 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @Stevers1 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 23:03 UTC, tresorsawasawa commented on index.html
> +
- [ **OPTIONAL** ] Kindly make sure your menu image button is wrapped in a `<nav>` tag as required for the project and for good HTML semantics. Make sure you add this change as it was missed by the previous reviewer

2022-06-30 23:03 UTC, tresorsawasawa commented on index.html
> +
- [ ] Good job making the change required by the previous reviewer. So, I noticed that you didn't update your styling once you added an `<a>` tag(check: the used correct color, no underline decoration on the text,...). Make sure you do so to stick to the Figma design.

2022-06-30 23:03 UTC, tresorsawasawa commented on index.html
> +      </div>
- [ ] As required by the previous reviewer kindly make sure each list of **Languages**, **Frameworks**, and **skills** uses a `<ul>` tag to group them, and `<li>` tag per item or element.
- [ ] Also make sure you add the list of **Skils** to all the content of the Figma template.

2022-06-30 23:03 UTC, tresorsawasawa commented on index.html
> +
- [ ] As mentioned by the previous reviewer, kindly make sure your project sticks to the Fitgma design as required for the project. Correctly check:
    - Fonts(font-size, font-weight, font-family, line-height,...)
    - Colors used on some text
    - Spacing between(margins && paddings) and around content
    - Adding all content(list of skills, some horizontal lines, all icons,...)
    - Add all background decorations and correctly align them
    - etc
### Figma Design 
![Homepage](https://user-images.githubusercontent.com/12524453/176752964-7468aeb3-2ac0-4011-87b8-68794ea9b2b3.png) 
### Your Design 
![Screenshot from 2022-07-01 00-52-59](https://user-images.githubusercontent.com/83042742/176791573-7e43be0e-367f-4fce-a59a-ae7966982c1f.png) |

2022-06-30 23:03 UTC, tresorsawasawa commented on styles.css
> +  /* border: 5px solid green; */
- [x] Kindly make sure you remove this commented code lines to make your project codebase cleaner

2022-06-30 23:03 UTC, tresorsawasawa commented on README.md
> +- GitHub: [@stevers1](https://github.com/Stevers1)
- [ ] As mentioned by the previous reviewer kindly make sure you use [the Microverse readme template](https://github.com/microverseinc/readme-template/blob/master/README.md)and make your README more professional. I suggest you take a look at [this README](https://github.com/tresorsawasawa/MyPortfolio/blob/develop/README.md) to help you how to fill out all the sections. I know you can do that :muscle: :muscle:

2022-06-30 23:10 UTC, tresorsawasawa commented
## NOTICE && IMPORTANT
 Kindly make sure you use the same **Pull request** and **branch** for your next review and not **Merge** or **Close** the **Pull request** before it is approved.

2022-07-02 16:03 UTC, Ginohmk approved these changes
Hi @Stevers1 , 

# STATUS: APPROVED 🟢

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 16:33 UTC, Stevers1 commented
Good to merge

2022-07-02 16:33 UTC, merged