Desktop version review
Stevers1/My-Portfolio pull request #5
Opened 2022-07-12 22:12 UTC by Stevers1

Review time :)

2022-07-12 23:30 UTC, codecaiine requested changes
Hi @Stevers1 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Descriptive Pull request :heavy_check_mark: 
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
- Great UI :heavy_check_mark:
- Clean code :heavy_check_mark:  

## Required Changes ♻️

- [ ] Please edit your pull request, your summary needs to reflect all the changes you made in your PR in order to guide the reviewer  :smile: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-12 23:30 UTC, codecaiine commented on styles.css
> +@media (min-width: 600px) {
- [ ] I noticed that your media query is too smaller :cry: . Please modify it cause you need to use media queries for the Desktop breakpoint in the CSS file which value for min-width property should be in range of 768px or wider . :+1:

2022-07-12 23:30 UTC, codecaiine commented on index.html
> +
- [ ]  Your hambuger menu icon for mobile version is diplaying instead of the Item Navigation aligned to the right for desktop version.  seem to have different styling compared to the Figma template, kindly change it so it looks similar to the Figma template :+1: 

- [ ] Your toolbar navigation links are missing, kindly change it so it looks similar to the Figma template

### Figma 
![Screenshot from 2022-07-12 22-36-27](https://user-images.githubusercontent.com/6615394/178610088-fb405769-0f15-423f-b21e-da0b13739af9.png)

### Your navigation
![Screenshot from 2022-07-12 22-32-20](https://user-images.githubusercontent.com/6615394/178610094-2a816ef4-79e5-4db1-ab24-b4c56df273da.png)




- [ ] Your row with social media icon-links  seems to have the wrong design compared to the Figma template as you can see below. Kindly adapt it so it conforms to the template provided :smile: 



### Figma template
![Screenshot from 2022-07-12 22-45-32](https://user-images.githubusercontent.com/6615394/178611451-d84bf34d-d5d9-4d8f-9a8b-f4af25d57ce6.png)

### Your project
![Screenshot from 2022-07-12 22-45-17](https://user-images.githubusercontent.com/6615394/178611457-78a1d46d-3d53-447c-b3bd-322ae8996f56.png)

2022-07-12 23:30 UTC, codecaiine commented on index.html
>      <h2>MY RECENT<br>WORK</h2>
- [ ] The "My recent work" text seems to have the wrong `width ` and `capitalization` of text compared to the Figma template as you can see below. Kindly change it so it conforms to the template provided :smile: 


### Figma template
![Screenshot from 2022-07-12 22-51-37](https://user-images.githubusercontent.com/6615394/178612199-a166f21a-c0d2-43f6-874a-df956cfda2a3.png)

### Your project
![Screenshot from 2022-07-12 22-51-23](https://user-images.githubusercontent.com/6615394/178612201-3b626b0f-d72b-4bc9-9e36-67e8a7effc78.png)

2022-07-12 23:30 UTC, codecaiine commented on index.html
>        </div>
- [ ]  The space between the project picture and project description is too much and the works section which does not match with the Figma design. Please fix it so it looks similar to the Figma design :+1: 

### Figma template
![Screenshot from 2022-07-12 22-58-06](https://user-images.githubusercontent.com/6615394/178613119-eb3a9b0c-b6e5-4b6a-a9b5-909c181df38c.png)

### Your project
![Screenshot from 2022-07-12 22-57-48](https://user-images.githubusercontent.com/6615394/178613122-5cd68cae-eecf-43c3-ae91-36c27b2c3a6e.png)

2022-07-12 23:30 UTC, codecaiine commented on index.html
>    </section>
- [ ] Please make sure that  your contact button looks similar to the Figma template, currently one of your buttons has different styling. :+1: 

- [ ] Please ensure taht the email after the social media icon links shares the same row as the social media icon links. :smile: 

### Figma template
![Screenshot from 2022-07-12 23-08-29](https://user-images.githubusercontent.com/6615394/178613818-9068bf69-e58a-4885-8a3f-08b8bf7563f1.png)

### Your project
![Screenshot from 2022-07-12 23-08-11](https://user-images.githubusercontent.com/6615394/178613819-23ce7db8-b603-41ab-ac9a-6fa49279707c.png)

2022-07-13 18:56 UTC, BertrandConxy requested changes
Hello @Stevers1  ✋, 

Great work on making the changes requested by a previous reviewer 👏 
I really appreciate your effort in improving your portfolio to look more outstanding. Keep it up 😎 👍 , but there are still some which aren't addressed yet.

 ## Highlights 💪 
- Project works well on my PC
- no linter errors
- correct GitHub flow is used


 ## Required Changes ♻️

- [ ] [OPTIONAL] It would be better if you add the screenshot of your portfolio landing page (Either mobile version or desktop version) so as to give visitors a quick preview of what your portfolio looks like 💡 
- [ ] [OPTIONAL] Please add a brief description of what you have done there in the Pull request description because it helps the reviewer to know what to review 💡 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-13 18:56 UTC, BertrandConxy commented on styles.css
> +@media (min-width: 600px) {
- [ ] It looks like you forgot to implement this suggestion requested by the previous reviewer. It is important to note that it is in **the project requirement to add the media queries** for the viewport `min-width equal to or greater than 768px` 😺. Please adjust this `min-width`

2022-07-13 23:31 UTC, vechicin approved these changes
# Hi @Stevers1 ✋, 

Your project is complete! 🎯 🧠 💯 
There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights ⚡ 

- [x] Good job implementing the previous reviewer's requirements.

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-13 23:31 UTC, vechicin commented on styles.css
> +  }
[OPTIONAL] You did not address the previous reviewer's requirements, please make sure you implement the required button styling.

2022-07-14 20:26 UTC, merged